"""test

Revision ID: 759f6a1fc1aa
Revises: a5485e51e2dc
Create Date: 2025-09-12 15:28:40.511138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '759f6a1fc1aa'
down_revision: Union[str, Sequence[str], None] = 'a5485e51e2dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('test', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('record', 'test')
    # ### end Alembic commands ###
