"""add user and add user_id for task

Revision ID: 7627e175c294
Revises: a32982df0b58
Create Date: 2025-10-16 16:44:34.759803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7627e175c294'
down_revision: Union[str, Sequence[str], None] = 'a32982df0b58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'record', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'record', type_='foreignkey')
    op.drop_column('record', 'user_id')
    # ### end Alembic commands ###
