"""test 2

Revision ID: a5dc91ed120b
Revises: 759f6a1fc1aa
Create Date: 2025-09-12 15:29:15.489309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5dc91ed120b'
down_revision: Union[str, Sequence[str], None] = '759f6a1fc1aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('record', 'test')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('test', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
