"""test 3

Revision ID: fee6f9d67f9d
Revises: a5dc91ed120b
Create Date: 2025-09-12 15:32:18.469708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fee6f9d67f9d'
down_revision: Union[str, Sequence[str], None] = 'a5dc91ed120b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('test', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('record', 'test')
    # ### end Alembic commands ###
